persistence:
  pg_url: postgresql://vandelay_app:secret@postgres:5432/vandelay
  redis:
    host: redis
    expires_in: 600 #seconds
integrations:
  vendors:
    one:
      api_base_url: mock_api_one:80
    two:
      api_base_url: mock_api_two:80
